services:
  app-prod:
    build:
      context: .
      target: prod
    init: true
    restart: always
    env_file:
      - ./environment/variables_prod.txt
    volumes:
      - prod-static-data:/vol/web
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-bullseye
    env_file:
      - ./environment/variables_prod.txt
    volumes:
      - prod-db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1",
        ]
      interval: 2s
      timeout: 6s
      retries: 2

  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - prod-static-data:/vol/static
    ports:
      - 80:8000
    depends_on:
      - app-prod

volumes:
  prod-db-data:
  prod-static-data:
