services:
  app-linting_testing_github:
    build:
      context: .
      target: linting_testing
    init: true
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-bullseye
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "localhost:5432"]
      interval: 2s
      timeout: 6s
      retries: 2

volumes:
  db-data:
  static-data:
