services:
  app-linting_testing_github:
    build:
      context: .
      target: linting_testing
    init: true
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-bullseye
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "curl", "-f", "http://localhost/ping", "||", "exit", "1"]
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  db-data:
  static-data:
