services:
  app-linting_testing_github:
    build:
      context: .
      target: linting_testing
    init: true
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15-bullseye
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  static-data:
