services:
  app-dev:
    build:
      context: .
      target: dev
    init: true
    env_file:
      - ./environment/variables.txt
    ports:
      - 8000:8000
    volumes:
      - ./app:/app:ro
  app-linting_testing:
    build:
      context: .
      target: linting_testing
    init: true
    env_file:
      - ./environment/variables.txt
    ports:
      - 8000:8000
  app-linting_testing_github:
    build:
      context: .
      target: linting_testing
    init: true
    environment:
      - SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
    ports:
      - 8000:8000
