# Generated by Django 3.2.13 on 2022-05-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
