name: Checks
on:
  push:
    branches:
      - dev
      - test

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test & Lint
        env:
          SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
        run: |
          docker-compose build --target app-linting_testing_github
          docker-compose up app-linting_testing_github
