name: Checks
on:
  push:
    branches:
      - dev
      - test

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test & Lint
        env:
          SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
          DEBUG_MODE: False
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          DB_HOST: ${{secrets.DB_HOST}}
        run: docker-compose -f docker-compose-actions.yaml up --build app-linting_testing_github
